services:
  ueransim:
    build: ./config
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - ./config:/mnt/ueransim
    expose:
      - "38412/sctp"
      - "2152/udp"
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    networks: 
      ueransim_vlan:
    env_file: ".env"
  
networks:
  ueransim_vlan:
    driver: macvlan
    driver_opts:
      parent: br-3e078ffa94f3
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16
          gateway: 172.22.1.254
          ip_range: 172.22.1.0/24
