# IMSI number of the UE. IMSI = [MCC|MNC|MSISDN] (In total 15 or 16 digits)
supi: 'imsi-UE_IMSI'
# Mobile Country Code value
mcc: 'MCC'
# Mobile Network Code value (2 or 3 digits)
mnc: 'MNC'

# Permanent subscription key
key: 'UE_KEY'
# Operator code (OP or OPC) of the UE
op: 'UE_OP'
# This value specifies the OP type and it can be either 'OP' or 'OPC'
opType: 'OPC'
# Authentication Management Field (AMF) value
amf: '8000'
# IMEI number of the device. It is used if no SUPI is provided
imei: 'UE_IMEI'

# List of gNB IP addresses for Radio Link Simulation
gnbSearchList:
  - GNB_N2_IP

# Initial PDU sessions to be established
sessions:
  - type: 'IPv4'
    apn: 'APN_NAME' #'internet'
    slice:
      sst: NSSAI_SST #1
      #sd: NSSAI_SD #000001
    emergency: false

# Configured NSSAI for this UE by HPLMN
configured-nssai:
  - sst: NSSAI_SST #1
    #sd: NSSAI_SD #000001

# Default Configured NSSAI for this UE
default-nssai:
  - sst: NSSAI_SST #1
    #sd: NSSAI_SD #000001

# Supported encryption algorithms by this UE
integrity:
  IA1: true
  IA2: true
  IA3: true

# Supported integrity algorithms by this UE
ciphering:
  EA1: true
  EA2: true
  EA3: true

# Integrity protection maximum data rate for user plane
integrityMaxRate:
  uplink: 'full'
  downlink: 'full'